// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD32xzXQ3mZ0E28zvFKE1lBMxEqVdZJmjQ',
    appId: '1:35237509417:web:95be7a122183dde5c79f38',
    messagingSenderId: '35237509417',
    projectId: 'my-first-project-e7a15',
    authDomain: 'my-first-project-e7a15.firebaseapp.com',
    databaseURL: 'https://my-first-project-e7a15-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-first-project-e7a15.appspot.com',
    measurementId: 'G-BT4M3DL0SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1zW3VnSfdvK3D3V_B34tVi8l4Qgtc5T0',
    appId: '1:35237509417:android:087de6c8f51512d1c79f38',
    messagingSenderId: '35237509417',
    projectId: 'my-first-project-e7a15',
    databaseURL: 'https://my-first-project-e7a15-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-first-project-e7a15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlHINv_IV9Rv9YivPfME0vofTeP_-Cv8U',
    appId: '1:35237509417:ios:d5c07bf94a7a385ac79f38',
    messagingSenderId: '35237509417',
    projectId: 'my-first-project-e7a15',
    databaseURL: 'https://my-first-project-e7a15-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-first-project-e7a15.appspot.com',
    androidClientId: '35237509417-iqvadn3klaij5hshgd1ccjg2b0i0u4ip.apps.googleusercontent.com',
    iosClientId: '35237509417-35n12rfj17d4stu0hmgi6uqtj1vqe4m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
