name: Run Tests

on:
  push:
    branches:
      - main  # Change this to match your branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Check test results
        run: |
          if [ $? -eq 0 ]; then
            echo "All tests passed!"
            exit 0
          else
            echo "Tests failed! Please fix the issues before pushing."
            exit 1
          fi
